# ---------------------- PROJECT SPECIFIC ---------------------------

site_name: Documentation
site_url: http://localhost/docs
repo_name: datajoint-company/datajoint-docs
repo_url: https://github.com/datajoint-company/datajoint-docs
nav:
  - Welcome: welcome.md
  - Core: core.md
  - Elements:
    - Overview: elements/index.md
    - Concepts: elements/concepts.md
    - User Instructions: elements/user-instructions.md
    - Developer Guide: elements/developer-instructions.md
    - Management:
        - Plan: elements/management/plan.md
        - Team: elements/management/team.md
        - Governance: elements/management/governance.md
        - Selection: elements/management/selection.md
        - Quality Assurance: elements/management/quality-assurance.md
        - Outreach: elements/management/outreach.md
        - Adopt: elements/management/adopt.md
  - Projects: projects.md
  - Publications: publications.md
  - Concepts:
    - Mantra: concepts/mantra.md
    - Query Language:
      - Datatypes: concepts/query-lang/datatypes.md
    - Referential Integrity:
        - Query Backend: concepts/ref-integrity/query-backend.md
  - Glossary: glossary.md
  - Citation: citation.md
  - Community:
    - Support: community/support.md
    - Events: community/events.md
    - Contribution: community/contribution.md
    - Licenses: community/licenses.md
    - Partnerships:
      - NWB: community/partnerships/nwb.md
      - DANDI: community/partnerships/dandi.md
      - Suite2p: community/partnerships/suite2p.md
      - Facemap: community/partnerships/facemap.md
      - INCF: community/partnerships/incf.md

# ---------------------------- STANDARD -----------------------------

docs_dir: ./src
edit_uri: ./edit/main/src
theme:
  font:
    text: Roboto Slab
    code: Source Code Pro
  name: material
  custom_dir: src/.overrides
  icon:
    logo: main/project-logo-black
  favicon: assets/images/project-logo-color.png
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "welcome.md"
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      options:
        custom_icons:
          - .overrides/.icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false # Disable watermark
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: main/company-logo
      link: https://www.datajoint.com/
    - icon: fontawesome/solid/ticket
      link: https://support.djneuro.io/portal/en/home
    - icon: fontawesome/brands/slack
      link: https://datajoint.slack.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datajoint
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DataJointIO
    - icon: fontawesome/brands/github
      link: https://github.com/datajoint
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/datajoint
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/datajointbot
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/datajoint
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCdeCuFOTCXlVMRzh6Wk-lGg
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://js-na1.hs-scripts.com/23133402.js  # HubSpot chatbot
